# Borrowed From https://taxintt.hatenablog.com/entry/2020/06/07/225215

site_name: My Docs

# materialのテーマを使用
theme:
  name: material
  language: ja
  features:
    - tabs
  palette:
    primary: indigo
    accent: indigo

# 拡張設定
markdown_extensions:
  - codehilite
  - footnotes
  - meta
  - admonition
  - mdx_math: # Write math
      enable_dollar_delimiter: true 
  - plantuml_markdown: # platnumlを書ける
      server: http://www.plantuml.com/plantuml
      format: svg
# mathjax Settings
extra_javascript: 
  - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

extra:
  search:
    language: 'ja'
plugins:
  - search # デフォルトだが一応明示的に
  #- git-revision-date-localized   # 更新時を表示可能


# ファイル構成
## docs 以下ならどこでもOK？要調査
nav:
  - Home:
    - Top: index.md
  - Chapters:
    - EquationTest: equation_test.md
    - AdmonitionTest: admonition_test.md
    - PlantUMLTest: uml_test.md